### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by qianyizhang** [NVIDIA/clara-viz#1]
RuntimeError: (/RenderServer/src/public/src/rs/hardware/nvenc/NvEncService.cpp:275) '' Runtime error Could not open nvEncodeAPI library

I am using python3.7 on ubuntu16.04

![image](https://user-images.githubusercontent.com/12500132/145138735-84dd5742-f66a-4775-b799-416fa22bbe50.png)

**Comment by AndreasHeumann** [comment]
Are you running in a docker container? If this is the case the 'video' driver capability has to be enabled when running the container, see https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/user-guide.html#driver-capabilities.
For example, use:
`docker run -it --rm -e NVIDIA_DRIVER_CAPABILITIES=graphics,video,compute,utility nvidia/cuda /bin/bash`
If this is not fixing the issue could you please give some more information on the environment you are running the A10 GPU? Are you using AWS?

**Comment by AndreasHeumann** [comment]
@qianyizhang Did this solve your issue?

**Comment by qianyizhang** [comment]
thanks for your response, i didn't try with docker. it was too much trouble to experiment with new feature
