### ISSUE TITLE
[BUG] pip install fails on Windows machines

### ISSUE THREAD

**Issue by IntegratorBrad** [NVIDIA/clara-viz#22]
**Describe the bug**
Installing Clara Viz on a pure Windows 11 machine fails because of dependency issues.
```
C:\dev\claraviz>pip install clara-viz
Collecting clara-viz
  Using cached clara_viz-0.2.1-py2.py3-none-any.whl (10 kB)
  Using cached clara_viz-0.1.4-py2.py3-none-any.whl (9.8 kB)
  Using cached clara_viz-0.1.3-py2.py3-none-any.whl (9.8 kB)
  Using cached clara_viz-0.1.2-py2.py3-none-any.whl (9.6 kB)
Collecting clara-viz-widgets==0.1.2
  Downloading clara_viz_widgets-0.1.2-py2.py3-none-any.whl (388 kB)
     ---------------------------------------- 388.6/388.6 kB 8.1 MB/s eta 0:00:00
Collecting clara-viz
  Using cached clara_viz-0.1.1-py2.py3-none-any.whl (9.4 kB)
  Using cached clara_viz-0.1.0-py2.py3-none-any.whl (8.4 kB)
ERROR: Cannot install clara-viz==0.1.0, clara-viz==0.1.1, clara-viz==0.1.2, clara-viz==0.1.3, clara-viz==0.1.4 and clara-viz==0.2.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    clara-viz 0.2.1 depends on clara-viz-core==0.2.1
    clara-viz 0.1.4 depends on clara-viz-core==0.1.4
    clara-viz 0.1.3 depends on clara-viz-core==0.1.3
    clara-viz 0.1.2 depends on clara-viz-core==0.1.2
    clara-viz 0.1.1 depends on clara-viz-core==0.1.1
    clara-viz 0.1.0 depends on clara-viz-core==0.1.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

```

**Steps/Code to reproduce bug**
On a Windows 11 machine, run `pip install clara-viz`

**Expected behavior**
If it runs on Windows 11, a successful installation is expected. 

If it won't run on Windows 11, it would be expected that:
1) this is documented on the landing page (beyond stating that WSL Windows Subsystem for Linux "Currently Clara Viz won't run under WSL because OptiX is not supported in that environment" which covers WSL but not base Windows installation) and 
2) the pip install fails with a message clearly stating operating system requirements aren't met.

**Environment details (please complete the following information)**

- OS/Platform: Windows 11
- Python Version: 3.10.6
- Clara Viz Version: main

**Comment by AndreasHeumann** [comment]
Hi Brad, sorry for the late reply, for some reason E-mail notifications on Clara Viz did not come through. I'll update the documentation mentioning the needed operating system.

**Comment by AndreasHeumann** [comment]
Updated the Readme with OS requirement `Linux x86_64`. Windows is not supported.
