### ISSUE TITLE
[BUG] Jupyter notebooks fail with `AttributeError: 'Widget' object has no attribute 'on_displayed'`

### ISSUE THREAD

**Issue by privatosan** [NVIDIA/clara-viz#23]
**Describe the bug**
When running the examples in Jupyter notebooks there is the error message `AttributeError: 'Widget' object has no attribute 'on_displayed'`.

**Steps/Code to reproduce bug**
Install Clara Viz, install Jupyter Notebooks, start Jupyter Notebooks, load and run the Jupyter Notebooks examples.

**Expected behavior**
Notebook examples should run as expected.

**Environment details (please complete the following information)**

- OS/Platform: Linux
- Python Version: 3.9
- Clara Viz Version: 0..2.1

**Additional context**

**Comment by AndreasHeumann** [comment]
Fixed with release 0.2.2.
