### ISSUE TITLE
ERROR occurs while running

### ISSUE THREAD

**Issue by OtisZZ** [NVIDIA/clara-viz#30]
Hi there,

Thanks for the great work in visualising the medical data.

There are three questions while I am using the repo:

1. ERROR occurs while running, but still can got the result. 
[ERROR] 2024-01-18 15:47:34.318 Render thread threw exception Not enough available display buffers
[ERROR] 2024-01-18 15:47:34.318 Not enough available display buffers

2. Also I have no idea how to stop or close a Renderer, the GPU memory is up and up while calling the Renderer by functions.

3. As the data was rendered on GPU, how can I sent in the data from GPU, rather than copy the data to host and render?

Thanks again for the great job!

**Comment by AndreasHeumann** [comment]
Hi,

> ERROR occurs while running, but still can got the result.
This error can be safely ignored. It occurs if the renderer is very fast and the task handling the render buffers can't keep up with the renderer. This might happen on the beginning of the rendering when no volume is displayed.

> Also I have no idea how to stop or close a Renderer, the GPU memory is up and up while calling the Renderer by functions.
How did you use the renderer? Could you provide steps or code? There is no such known issue with the examples provided.

> As the data was rendered on GPU, how can I sent in the data from GPU, rather than copy the data to host and render?
I'm not sure if I can follow. Could you give a code example?
The example here https://github.com/NVIDIA/clara-viz/blob/main/src/examples/claravizrenderer-ui/Main.cpp#L487 get's data back from the renderer in GPU memory.
The volume data is provided as IBlob derived data, this can be GPU or CPU data. For example the  volume stream renderer provides the data using a CudaMemoryBlob in GPU memory here https://github.com/NVIDIA/clara-viz/blob/main/src/examples/volumestreamrenderer/DataSourceCT.cpp#L122.
