### ISSUE TITLE
image_type=clara.viz.core.ColorImageType.RAW_RGBA_U8[BUG] Segfault with render_image, 

### ISSUE THREAD

**Issue by thewtex** [NVIDIA/clara-viz#33]
I get a segfault when trying the *Render CT data from Python* example in the README:

https://github.com/NVIDIA/clara-viz/tree/main/python#render-ct-data-from-python

ColorImageType.JPEG from the Render_image.ipynb notebook does work fine.

**Comment by AndreasHeumann** [comment]
Thanks for reporting the issue. I'll try to reproduce it on my side.

**Comment by AndreasHeumann** [comment]
Hi @thewtex, I checked this locally and rendering RGBA images works fine. Could you share more information? Do you have example code you can share?

**Comment by AndreasHeumann** [comment]
I've now been able to reproduce the crash, I'm working on a fix.

**Comment by AndreasHeumann** [comment]
Fixed in release 0.4.0. Closing.

**Comment by thewtex** [comment]
@AndreasHeumann thank you!
