### ISSUE TITLE
[BUG] Python sources not present in the repository

### ISSUE THREAD

**Issue by thewtex** [NVIDIA/clara-viz#34]
I am interested in contributing to the `DataCollection` class, found in the published package, but the sources are not found in this repository as far as I can see.

In particular, I would like to expand on the ITK Python IO support to support [`itkwasm-image-io`](https://insightsoftwareconsortium.github.io/itk-wasm/image-io/py/docs/), which lighter and possibly faster. Also [`itkwasm.Image`](https://wasm.itk.org/en/latest/python/numpy.html) in-memory support. And, [ngff-zarr multiscale image support](https://ngff-zarr.readthedocs.io/en/latest/), which can be backed by ITK Python, ITK-Wasm, cuCIM, and more.

**Comment by AndreasHeumann** [comment]
Hi Matt,
thanks for planning to contribute! Yes, the Python sources are not yet included in the repo. I'll work on updating the repo to update it hopefully soon with the Python sources.
Thanks,
Andreas
