### ISSUE TITLE
Add a flag to disable `nvjpeg` support

### ISSUE THREAD

**Issue by tbirdso** [NVIDIA/clara-viz#48]
**Is your feature request related to a problem? Please describe.**

I would like to build an application ([HoloHub's `volume_rendering_xr`](https://github.com/nvidia-holoscan/holohub/tree/main/applications/volume_rendering_xr)) with ClaraViz in a build environment, and then deploy it in a lightweight `cuda-base` runtime container without build dependencies. However, I'm encountering an issue where ClaraViz eagerly links in build environment libraries that are not available in the target runtime environment, leading to `ldd` failures.

Specifically, `nvjpeg` is always linked in if it is found in the build environment:

https://github.com/NVIDIA/clara-viz/blob/main/src/claraviz/CMakeLists.txt#L105

https://github.com/NVIDIA/clara-viz/blob/main/src/claraviz/CMakeLists.txt#L177

**Describe the solution you'd like**

To my knowledge the `volume_rendering_xr` application does not exercise `nvjpeg`. I would like to be able to pass a CMake configuration option to ClaraViz to manually disable `nvjpeg` and prevent it from being linked to the application, i.e.:

```bash
cmake -S ../clara-viz -B . -DUSE_NVJPEG:BOOL="False"
```

**Describe alternatives you've considered**

Under current behavior I have the option of either:
- Enforcing that the build and runtime containers both provide `nvjpeg`. This could be accomplished with the HoloHub build container + `cuda-runtime` NGC container. The disadvantage of this is that the `cuda-runtime` container appears to be larger than the `cuda-base` container by at least 1GB.
- Enforcing that neither the build nor runtime container provides `nvjpeg`. This could be accomplished with the `cuda-base` NGC container, but would be less standardized and require more build container setup than the HoloHub container.

`nvjpeg` appears to be the only library that the application is missing in `cuda-base` versus `cuda-runtime`.

**Additional context**

**Comment by AndreasHeumann** [comment]
Thanks for the suggestion.
There is another option for a minimal docker image. You could also use OS base image and install CUDA with deb packages like here https://github.com/NVIDIA/clara-viz/blob/main/Dockerfile_x86_64.build#L20. This is for CentOS and using the -dev images but it should be similar for Ubuntu.
Making nvjpeg optional is not that trivial because it has to be handled cleanly by the ClaraViz API as well.

**Comment by tbirdso** [comment]
Thanks for the details and suggestions @AndreasHeumann , sounds like I misunderstood the level of effort required. I'll close this as not planned in ClaraViz and explore the workaround you've suggested separately.
