### ISSUE TITLE
DOUBT

### ISSUE THREAD

**Issue by NonlinearNimesh** [NVIDIA/clara-viz#5]
Hi,
Can we do server-side rendering in Clara-viz ?

Thanks

**Comment by AndreasHeumann** [comment]
Hi,
yes, you can do server-side rendering using JupyterLab. Additionally we plan to release render server with a gRPC interface and a web based viewer using the render server.

**Comment by NonlinearNimesh** [comment]
Thanks
Is there any documentation where I can found how i can do the server side rendering using Clara viz ?

**Comment by AndreasHeumann** [comment]
No, there is no documentation on how to use Clara Viz with Jupyter Lab. But basically go to the server install Clara Viz examples, Clara Viz and Jupyter Lab and then start the Jupter Lab server.
```
pip install clara-viz jupyterlab
jupyter lab --no-browser --ip=*
```
Then on the client open a browser and go to the server ip address on port 8888.
For the gRPC interface we'll release the documentation once the feature is released.

**Comment by NonlinearNimesh** [comment]
Thanks,

One last ques,
Can you please list down the advantage of using Clara Viz 
Actually for now all I know is clara viz is good in visualization.

**Comment by AndreasHeumann** [comment]
When you are talking about advantages then I need to know with which product you are comparing Clara Viz.

Clara Viz has an easy to use Python interface and provides fast GPU accelerated cinematic rendering of volumes. It also supports original slice rendering and segmentation masks.

**Comment by NonlinearNimesh** [comment]
Actually I am not comparing with any others for now, i came across clara viz is when I was thinking of rendering mamogram in the server itself. Which you clearly mentioned that it will.

And, also one thing I want to 

Can clara viz do "volume rendering in browser" itself, considering mamogram is of high sizes

**Comment by AndreasHeumann** [comment]
>Can clara viz do "volume rendering in browser" itself, considering mamogram is of high sizes
No, the data always needs to be transferred o the server where Clara Viz is running. The renderer can't run in the browser.

**Comment by NonlinearNimesh** [comment]
Thanks a lot

**Comment by NonlinearNimesh** [comment]
Hi, Is there any way i can run clara viz in google colab ?

**Comment by AndreasHeumann** [comment]
Yes, theoretically it should work. But when I tried it the GPU assigned to my instance was a K80 which is pretty old. Clara Viz at least needs a GPU from the Pascal generation or newer.

**Comment by NonlinearNimesh** [comment]
Thanks,
And, can I use Clara viz for streaming medical data. For example, let say I have CT scan in which i agve roughly around 300 CTs. Right now when i try to go through in a viewer it lags while loading. Can clara viz solve this problem.

 In a nutshell i want to build a viewer where i want lagging part to be minimal.

**Comment by AndreasHeumann** [comment]
If you have the CT data on the server which is also doing the rendering then load time is minimal. For a normal CT scan the time from starting the loading process to the first rendered image is less than a second.
